version: "3"

services:
  postgres:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache_redis:/data

  smtp4dev:
    container_name: smtp
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # web interface
      - '5000:80'
      # SMTP
      - '25:25'
      # IMAP
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

  celery:
    build:
      context: .
    env_file:
      - .env
    command: [ "/app/docker/celery.sh", "celery" ]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env
    command: [ "/app/docker/celery.sh", "flower" ]
    depends_on:
      - redis
      - celery
    ports:
      - "8888:5555"

  app:
    build: .
    env_file:
      - .env
    command: [ "/app/docker/api.sh" ]
    ports:
      - '8000:8000'

volumes:
    data_postgres:
    cache_redis:
    smtp4dev-data:
