version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache_redis:/data

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # web interface
      - '5000:80'
      # SMTP
      - '25:25'
      # IMAP
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
    data_postgres:
    cache_redis:
    smtp4dev-data:
