"""add phone user

Revision ID: 256618588ba7
Revises: 4b2aaa57d47c
Create Date: 2023-04-12 17:54:45.709181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256618588ba7'
down_revision = '4b2aaa57d47c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
