"""Add del cascade

Revision ID: 370d874198e6
Revises: 9e0067ba16cc
Create Date: 2023-05-26 17:14:40.387396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370d874198e6'
down_revision = '9e0067ba16cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_user_id_fkey', 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('password_group_id_fkey', 'password', type_='foreignkey')
    op.create_foreign_key(None, 'password', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password', type_='foreignkey')
    op.create_foreign_key('password_group_id_fkey', 'password', 'group', ['group_id'], ['id'])
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key('group_user_id_fkey', 'group', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
