"""column description

Revision ID: 83bd77050a56
Revises: faaf4f769089
Create Date: 2023-05-26 17:45:00.822977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bd77050a56'
down_revision = 'faaf4f769089'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_data',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('service_name', sa.String(length=512), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=2048), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_name', 'login', 'group_id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('auth_date')
    op.add_column('group', sa.Column('description', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'description')
    op.create_table('auth_date',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('login', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='auth_date_group_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_name', 'login', 'group_id', name='auth_date_pkey'),
    sa.UniqueConstraint('id', name='auth_date_id_key')
    )
    op.drop_table('auth_data')
    # ### end Alembic commands ###
