"""Added table Password

Revision ID: 9e0067ba16cc
Revises: 49de5c22d90e
Create Date: 2023-05-21 21:45:11.527748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0067ba16cc'
down_revision = '49de5c22d90e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('service_name', sa.String(length=512), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=2048), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('service_name', 'login', 'group_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password')
    # ### end Alembic commands ###
