"""Change name table

Revision ID: faaf4f769089
Revises: 370d874198e6
Create Date: 2023-05-26 17:19:57.150752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faaf4f769089'
down_revision = '370d874198e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_date',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('service_name', sa.String(length=512), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=2048), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_name', 'login', 'group_id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('login', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='password_group_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_name', 'login', 'group_id', name='password_pkey'),
    sa.UniqueConstraint('id', name='password_id_key')
    )
    op.drop_table('auth_date')
    # ### end Alembic commands ###
